stages:       
  - secrets
  - test
  - test1

variables:
  CONFIG: $CONFIG


secrets:
  stage: secrets
  image: vault
  variables:
    CONFIG: "$(vault kv get -field=data -format=yaml jobpass/ops/development/back/config)"
  before_script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=jobpass-development jwt=$CI_JOB_JWT)"
    - export CONFIG="$(vault kv get -field=data -format=yaml jobpass/ops/development/back/config)"
  script:
    - echo "$CONFIG" > config.yaml
  artifacts:
    config.yaml

test:
  dependencies:
    - "secrets"
  stage: test
  script:
    - cat config.yaml

test1:
  variables: {}
  stage: test1
  script:
    - echo "$CONFIG"


