stages:       
  - secrets
  - test
  - test1

secrets:
  stage: secrets
  image: vault
  script:
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_REF_PROTECTED
    - if [[  "$CI_COMMIT_REF_NAME" == "master" ]]
    - then echo works
    - fi
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=jobpass-development jwt=$CI_JOB_JWT)"
    - export CONFIG="$(vault kv get -field=data -format=yaml jobpass/ops/development/back/config)"
    - echo "$CONFIG" > test
    - cat test
    - echo "${CONFIG}" > test
    - cat test


test:
  stage: test
  script:
    - echo "$CONFIG" > test
    - cat test
    - echo "${CONFIG}" > test
    - cat test


test1:
  stage: test1
  script:
    - echo "$CONFIG" > test
    - cat test
    - echo "${CONFIG}" > test
    - cat test


